import type { Metadata } from "next";
import { ubuntu,montserrat } from "@/components/fonts/fonts";
import "./globals.css";
import Navbar from "@/components/main/Navbar";
import Hero from "@/components/main/Hero";
import Cards from "@/components/main/Cards";
import Providers from "./providers";
import Footer from "@/components/main/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-[#F9F6F6] overflow-y-scroll overflow-x-hidden`}>
       <Providers>
        <Navbar/>
        <Hero/>
        <Cards/>
         {children}
         <Footer/>
       </Providers>
      </body>
    </html>
  );
}
